"""initial news schema

Revision ID: d80efae9a0c9
Revises: 
Create Date: 2026-09-11 17:21:08.558209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Autogenerate emits the embedding column fully qualified, as
# pgvector.sqlalchemy.vector.VECTOR(dim=1024), so this module must be
# imported under that exact name.
import pgvector.sqlalchemy


revision: str = 'd80efae9a0c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # signals.embedding is a pgvector column, so the extension has to
    # exist before that table is created. Done here rather than in
    # scripts/init-second-db.sh so it also applies on RDS, where that
    # container init script never runs.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('signal_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('signals_fetched', sa.Integer(), nullable=False),
    sa.Column('signals_passed_rules', sa.Integer(), nullable=False),
    sa.Column('signals_passed_llm', sa.Integer(), nullable=False),
    sa.Column('signals_sent', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('full_content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('applicability_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('filter_justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    op.drop_table('stats')
    op.drop_table('batches')
    # ### end Alembic commands ###

    # Deliberately NOT dropping the vector extension: it is a
    # database-level object, and DROP EXTENSION would cascade into any
    # other vector column in this database.
