"""index signals.url

Revision ID: 144fbb1818ea
Revises: 33e0ab9276f5
Create Date: 2026-09-12 10:25:16.821806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# The News DB's signals table has a pgvector embedding column.
# Autogenerate emits it fully qualified, as
#   pgvector.sqlalchemy.vector.VECTOR(dim=1024)
# but never adds the import itself, so the generated file would raise
# NameError on import. Kept in the template so every News migration
# has it available rather than needing it hand-added each time.
import pgvector.sqlalchemy


revision: str = '144fbb1818ea'
down_revision: Union[str, None] = '33e0ab9276f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_signals_url'), 'signals', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_url'), table_name='signals')
    # ### end Alembic commands ###
