"""unique url, unsent composite, hnsw embedding

Revision ID: 577d8ecbadf8
Revises: 144fbb1818ea
Create Date: 2026-09-12 10:31:09.293341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# The News DB's signals table has a pgvector embedding column.
# Autogenerate emits it fully qualified, as
#   pgvector.sqlalchemy.vector.VECTOR(dim=1024)
# but never adds the import itself, so the generated file would raise
# NameError on import. Kept in the template so every News migration
# has it available rather than needing it hand-added each time.
import pgvector.sqlalchemy


revision: str = '577d8ecbadf8'
down_revision: Union[str, None] = '144fbb1818ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_url', table_name='signals')
    op.create_index('ix_signals_url', 'signals', ['url'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_signals_embedding_hnsw', 'signals', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_signals_unsent', 'signals', ['is_sent', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_unsent', table_name='signals')
    op.drop_index('ix_signals_embedding_hnsw', table_name='signals', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_signals_url', table_name='signals', postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_signals_url', 'signals', ['url'], unique=False)
    # ### end Alembic commands ###
