"""conversation indexes

Revision ID: 39fa928b6fcc
Revises: 4738e95a710a
Create Date: 2026-09-12 10:36:19.114342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '39fa928b6fcc'
down_revision: Union[str, None] = '4738e95a710a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_daily_costs_user_date', 'daily_costs', ['user_id', 'date'])
    op.create_index('ix_messages_user_timestamp', 'messages', ['user_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_user_timestamp', table_name='messages')
    op.drop_constraint('uq_daily_costs_user_date', 'daily_costs', type_='unique')
    # ### end Alembic commands ###
